apiVersion: v1
kind: Service
metadata:
  name: weaviate
  namespace: dify
spec:
  selector:
    app: weaviate
  type: ClusterIP
  ports:
  - name: weaviate
    protocol: TCP
    port: 8080
    targetPort: 8080
