apiVersion: v1
kind: Service
metadata:
  name: sandbox
  namespace: dify
spec:
  ports:
  - port: 8194
    targetPort: 8194
    protocol: TCP
    name: sandbox
  type: ClusterIP
  selector:
    app: sandbox
